menu:
  Home: http://fireball-x.com
  Docs: /
  API: /api/modules/Fire.html

menu_zh:
    首页: http://fireball-x.com
    用户文档: /zh
    API: /api/zh/modules/Fire.html

doc_sidebar:
  Getting Started:
      Overview: en/dev
      Setup: en/dev/setup
  Core:
      Script-Building: en/dev/core/script-building
      Serialization: en/dev/core/serialization
  Editor:
      Editor Startup: en/dev/editor/editor
      Editor Arguments: en/dev/editor/editor-arguments
      Editor Events: en/dev/editor/editor-events
      Node Modules: en/dev/editor/node-modules
      AssetDatabase: en/dev/editor/asset-db
      Share Library: en/dev/editor/share
      Init Quick Window: en/dev/editor/init-quick-window

doc_sidebar_zh:
    新手上路:
        简介: zh/dev
        安装开发环境: zh/dev/setup
    核心:
        脚本编译: zh/dev/core/script-building
        序列化: zh/dev/core/serialization
    Editor编辑器:
        Editor启动流程: zh/dev/editor/editor
        Editor运行参数: zh/dev/editor/editor-arguments
        Editor事件: zh/dev/editor/editor-events
        Node Modules: zh/dev/editor/node-modules
        AssetDB资源数据库: zh/dev/editor/asset-db
        Share文件夹: zh/dev/editor/share
        Quick Window 初始化流程: zh/dev/editor/init-quick-window


user_sidebar:
    Getting Started:
        Get Fireball: #
        Create a Project: #
        From Unity: en/start/from-unity
        Help: en/help
    User Manual:
        Know the Editor: #
        Asset Pipeline: #
    Scripting:
        Creating and Using Scripts: #
        Accessing Objects: #
        Component Callbacks: #
        Creating and Destroying Objects: #
        Time and Framerate: #
        Class: #
        Attributes: #
        Module: #
        Reserved Words: en/scripting/reserved-words

user_sidebar_zh:
    新手上路:
        获取Fireball: zh/start/get-fireball
        新建项目: zh/start/new-project
        Unity开发者上手: zh/start/from-unity
        帮助: zh/help
    用户手册:
        认识Editor: zh/start/editor-overview
        资源工作流程: #
    脚本编写:
        创建和使用脚本: zh/scripting/component
        对象访问: zh/scripting/component/access
        Component回调: zh/scripting/component/callbacks
        创建和销毁对象: zh/scripting/create-destroy-entities
        计时和帧率: zh/scripting/time
        类型定义: zh/scripting/class
        属性参数: zh/scripting/attributes
        模块化: zh/scripting/module
        附录：保留字: zh/scripting/reserved-words
    插件开发:
        配置Package.json: zh/plugin/config-package-json

google_analytics:
fb_admins:
swiftype_key: grCydSzsxUXshDXhE5sR
twitter: fireballengine
github: fireball-x/docs
