menu:
  Home: http://fireball-x.com
  Docs: /
  Developer: /docs/en/dev
  API: /docs/api

menu_zh:
    首页: http://fireball-x.com
    用户文档: /zh
    开发者文档: /docs/zh/dev
    API: /docs/api

doc_sidebar:
  Getting Started:
      Overview: en/dev
      Setup: en/dev/setup
  Core:
      Class: en/dev/core/class
      Script-Building: en/dev/core/script-building
      Serialization: en/dev/core/serialization
  Editor:
      Editor Startup: en/dev/editor/editor
      Editor Arguments: en/dev/editor/editor-arguments
      Editor Events: en/dev/editor/editor-events
      Node Modules: en/dev/editor/node-modules
      AssetDatabase: en/dev/editor/asset-db
      Share Library: en/dev/editor/share

doc_sidebar_zh:
    新手上路:
        简介: zh/dev
        设置: zh/dev/setup
    核心:
        类型定义: zh/dev/core/class
        脚本编译: zh/dev/core/script-building
        序列化: zh/dev/core/serialization
    Editor编辑器:
        Editor启动流程: zh/dev/editor/editor
        Editor运行参数: zh/dev/editor/editor-arguments
        Editor事件: zh/dev/editor/editor-events
        Node Modules: zh/dev/editor/node-modules
        AssetDB资源数据库: zh/dev/editor/asset-db
        Share文件夹: zh/dev/editor/share


user_sidebar:
    Getting Started:
        Get Fireball: en/start/install
        Create a Project: en/start/new-project
        Help: en/help
    User Manual:
        Know the Editor: en/manual/editor
        Asset Pipeline: en/manual/assets
    Scripting:
        Module: en/scripting/module

user_sidebar_zh:
    新手上路:
        获取Fireball: zh/start/install
        新建项目: zh/start/new-project
        帮助: zh/help
    用户手册:
        认识Editor: zh/manual/editor
        资源工作流程: zh/manual/assets
    脚本编写:
        模块化: zh/scripting/module

google_analytics:
fb_admins:
swiftype_key: WM9aFPtvcpZwMuaRj9Yc
twitter: hexojs
github: fireball-x/docs
